
RGraph=window.RGraph||{isrgraph:true,isRGraph:true,rgraph:true};RGraph.SVG=RGraph.SVG||{};RGraph.SVG.HTML=RGraph.SVG.HTML||{};(function(win,doc,undefined)
{RGraph.SVG.drawKey=function(obj)
{var properties=obj.properties,key=properties.key,colors=properties.keyColors||properties.colors,defaultFont='Arial',blobSize=0,width=0,keyColorShape=properties.keyColorShape;var centerx=obj.svg.getAttribute('width')/2;if(obj.type==='funnel'){centerx=(obj.graphWidth/2)+properties.marginLeft;}
if(key&&key.length){for(var i=0,length=0;i<key.length;i++){var textDimensions=RGraph.SVG.measureText({text:key[i],italic:properties.keyLabelsItalic||properties.textItalic,bold:properties.keyLabelsBold||properties.textBold,font:properties.keyLabelsFont||properties.textFont||defaultFont,size:properties.keyLabelsSize||properties.textSize,cache:false});blobSize=Math.max(blobSize,textDimensions[1]);width=width+10+blobSize+5+textDimensions[0];}
x=centerx-width/2;var textConf=RGraph.SVG.getTextConf({object:obj,prefix:'keyLabels'});for(var i=0,y=properties.marginTop-5;i<key.length;++i){if(i===0){if(obj.type==='pie'&&properties.highlightStyle=='outline'){y-=properties.highlightStyleOutlineWidth;}}
var textDimensions=RGraph.SVG.measureText({text:key[i],italic:properties.keyLabelsItalic||properties.textItalic,bold:properties.keyLabelsBold||properties.textBold,font:properties.keyLabelsFont||properties.textFont||defaultFont,size:properties.keyLabelsSize||properties.textSize,cache:false});var shape=properties.keyColorShape;if(typeof shape==='object'){shape=properties.keyColorShape[i];}
if(shape==='circle'){RGraph.SVG.create({svg:obj.svg,type:'circle',parent:obj.svg.all,attr:{cx:x+(blobSize/2)+properties.keyOffsetx,cy:y-(blobSize/2)+properties.keyOffsety,r:blobSize/2,fill:colors[i]}});}else if(shape==='triangle'){RGraph.SVG.create({svg:obj.svg,type:'path',parent:obj.svg.all,attr:{d:'M {1} {2} L {3} {4} L {5} {6} z'.format(x+properties.keyOffsetx+(blobSize/2),y-blobSize+properties.keyOffsety,x+properties.keyOffsetx+blobSize,y+properties.keyOffsety,x+properties.keyOffsetx,y+properties.keyOffsety),fill:colors[i]}});}else if(shape==='line'){RGraph.SVG.create({svg:obj.svg,type:'path',parent:obj.svg.all,attr:{d:'M {1} {2} L {3} {4}'.format(x+properties.keyOffsetx,y-(blobSize/2)+properties.keyOffsety,x+properties.keyOffsetx+blobSize,y-(blobSize/2)+properties.keyOffsety),stroke:colors[i],'stroke-width':2,'stroke-linecap':'round'}});}else if(shape==='dot'){RGraph.SVG.create({svg:obj.svg,type:'path',parent:obj.svg.all,attr:{d:'M {1} {2} L {3} {4}'.format(x+properties.keyOffsetx,y-(blobSize/2)+properties.keyOffsety,x+properties.keyOffsetx+blobSize,y-(blobSize/2)+properties.keyOffsety),stroke:colors[i],'stroke-width':2,'stroke-linecap':'round'}});RGraph.SVG.create({svg:obj.svg,type:'circle',parent:obj.svg.all,attr:{cx:x+(blobSize/2)+properties.keyOffsetx,cy:y-(blobSize/2)+properties.keyOffsety,r:blobSize/4,fill:colors[i]}});}else if(shape==='squaredot'||shape==='rectdot'){RGraph.SVG.create({svg:obj.svg,type:'path',parent:obj.svg.all,attr:{d:'M {1} {2} L {3} {4}'.format(x+properties.keyOffsetx,y-(blobSize/2)+properties.keyOffsety,x+properties.keyOffsetx+blobSize,y-(blobSize/2)+properties.keyOffsety),stroke:colors[i],'stroke-width':2,'stroke-linecap':'round'}});RGraph.SVG.create({svg:obj.svg,type:'rect',parent:obj.svg.all,attr:{x:x+(blobSize/4)+properties.keyOffsetx,y:y+(blobSize/4)-blobSize+properties.keyOffsety,width:blobSize/2,height:blobSize/2,fill:colors[i]}});}else if(typeof shape==='function'){RGraph.SVG.create({svg:obj.svg,type:'path',parent:obj.svg.all,attr:{d:'M {1} {2} L {3} {4}'.format(x+properties.keyOffsetx,y-(blobSize/2)+properties.keyOffsety,x+properties.keyOffsetx+blobSize,y-(blobSize/2)+properties.keyOffsety),stroke:colors[i],'stroke-width':2,'stroke-linecap':'round'}});}else{RGraph.SVG.create({svg:obj.svg,type:'rect',parent:obj.svg.all,attr:{x:x+properties.keyOffsetx,y:y-blobSize+properties.keyOffsety,width:blobSize,height:blobSize,fill:colors[i]}});}
RGraph.SVG.text({object:obj,parent:obj.svg.all,tag:'key',size:textConf.size,bold:textConf.bold,italic:textConf.italic,font:textConf.font,color:textConf.color,halign:'left',valign:'bottom',text:key[i],x:x+blobSize+5+properties.keyLabelsOffsetx+properties.keyOffsetx,y:y+properties.keyLabelsOffsety+properties.keyOffsety,background:properties.keyLabelsBackground||'white',padding:0})
x+=10+blobSize+5+textDimensions[0];}}};RGraph.SVG.HTML.key=function(id,properties)
{var div=doc.getElementById(id);var str='<table border="0" cellspacing="0" cellpadding="0" id="rgraph_key" style="display: inline;'+(function()
{var style=''
for(i in properties.tableCss){if(typeof i==='string'){style=style+i+': '+properties.tableCss[i]+';';}}
return style;})()+'" '+(properties.tableClass?'class="'+properties.tableClass+'"':'')+'>';for(var i=0;i<properties.labels.length;i+=1){str+='<tr><td><div style="'+(function()
{var style='';for(var j in properties.blobCss){if(typeof j==='string'){style=style+j+': '+properties.blobCss[j]+';';}}
return style;})()+'display: inline-block; margin-right: 5px; margin-top: 4px; width: 15px; height: 15px; background-color: '+properties.colors[i]+'"'+(properties.blobClass?'class="'+properties.blobClass+'"':'')+'>&nbsp;</div><td>'+(properties.links&&properties.links[i]?'<a href="'+properties.links[i]+'">':'')+'<span '+(properties.labelClass?'class="'+properties.labelClass+'"':'')+'" style="'+(function()
{var style='';for(var j in properties.labelCss){if(typeof j==='string'){style=style+j+': '+properties.labelCss[j]+';';}}
return style;})()+'" '+(function()
{var style='';if(properties['labelCss_'+i]){for(var j in properties['labelCss_'+i]){style=style+j+': '+properties['labelCss_'+i][j]+';';}}
return style?'style="'+style+'"':'';})()+'>'+properties.labels[i]+'</span>'+(properties.links&&properties.links[i]?'</a>':'')+'</td></tr>';}
div.innerHTML+=(str+'</table>');return doc.getElementById('rgraph_key');};})(window,document);